name: flutter_super_html_viewer
description: A Flutter plugin that provides a HtmlViewer widget on multiple platforms
homepage: https://github.com/dab246/flutter_super_html_viewer.git
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  flutter_inappwebview: ^6.0.0-beta.22

  url_launcher: ^6.1.10

  universal_html: ^2.0.9

  webview_windows: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
